### ISSUE TITLE
Any way to hide Seconds, and show AM/PM?

### ISSUE THREAD

**Issue by parmarkamlesh** [JongtaekChoi/react-native-time-picker#1]
hi is there any prop or something to hide seconds and display AM PM ?

**Comment by JongtaekChoi** [comment]
Thanks for your interest.

Both not yet. I think it's not difficult to implement it by referring to  [src/TImePicker.tsx](https://github.com/JongtaekChoi/react-native-time-picker/blob/main/src/TImePicker.tsx). 

I'll try after I have time.

**Comment by JongtaekChoi** [comment]
Now, the default option changed to hide seconds and use a 24-hour system.
