### ISSUE TITLE
Is there anyway to move from AM/PM from left side to right side?

### ISSUE THREAD

**Issue by elliotching** [JongtaekChoi/react-native-time-picker#2]
I need to show AM/PM at right side of HOUR/MIN wheels

**Comment by JongtaekChoi** [comment]
In this version (0.5.0), timeFormat was added to TimePicker props. This property is the list type of TimeType enum or string and is used to determine the order of Wheel components to display. The default value is [TimeType.ampm, TimeType.hours12, ':', TimeType.min], and if you want am/pm to be displayed on the right, enter [TimeType.hours12, ':', TimeType.min, TimeType.ampm].
